import {RelationTargetBase} from "crom_l1_composed/RelationTargetBase";
import {ParameterBase} from "crom_l1_composed/ParameterBase";
import {Constraint} from "crom_l1_composed/Constraint";
import {RoleType} from "crom_l1_composed/RoleType";
import {Inheritance} from "crom_l1_composed/Inheritance";
import {Irreflexive} from "crom_l1_composed/Irreflexive";
import {DataInheritance} from "crom_l1_composed/DataInheritance";
import {IrreflexiveBase} from "crom_l1_composed/IrreflexiveBase";
import {RelationshipConstraintBase} from "crom_l1_composed/RelationshipConstraintBase";
import {RelationBase} from "crom_l1_composed/RelationBase";
import {TotalBase} from "crom_l1_composed/TotalBase";
import {CompartmentInheritance} from "crom_l1_composed/CompartmentInheritance";
import {DataTypeBase} from "crom_l1_composed/DataTypeBase";
import {InheritanceBase} from "crom_l1_composed/InheritanceBase";
import {RoleConstraintBase} from "crom_l1_composed/RoleConstraintBase";
import {RoleInheritance} from "crom_l1_composed/RoleInheritance";
import {OperationBase} from "crom_l1_composed/OperationBase";
import {CompartmentInheritanceBase} from "crom_l1_composed/CompartmentInheritanceBase";
import {NaturalTypeBase} from "crom_l1_composed/NaturalTypeBase";
import {InterRelationshipConstraintBase} from "crom_l1_composed/InterRelationshipConstraintBase";
import {Fulfillment} from "crom_l1_composed/Fulfillment";
import {InterRelationshipConstraint} from "crom_l1_composed/InterRelationshipConstraint";
import {ComplexConstraintBase} from "crom_l1_composed/ComplexConstraintBase";
import {NaturalInheritance} from "crom_l1_composed/NaturalInheritance";
import {NaturalInheritanceBase} from "crom_l1_composed/NaturalInheritanceBase";
import {AntiRigidType} from "crom_l1_composed/AntiRigidType";
import {RelationshipExclusionBase} from "crom_l1_composed/RelationshipExclusionBase";
import {ComplexConstraint} from "crom_l1_composed/ComplexConstraint";
import {Group} from "crom_l1_composed/Group";
import {RelationshipConstraint} from "crom_l1_composed/RelationshipConstraint";
import {Attribute} from "crom_l1_composed/Attribute";
import {TypedElement} from "crom_l1_composed/TypedElement";
import {TypeBase} from "crom_l1_composed/TypeBase";
import {CompartmentTypeBase} from "crom_l1_composed/CompartmentTypeBase";
import {Operation} from "crom_l1_composed/Operation";
import {ConstraintBase} from "crom_l1_composed/ConstraintBase";
import {CyclicBase} from "crom_l1_composed/CyclicBase";
import {FulfillmentBase} from "crom_l1_composed/FulfillmentBase";
import {Relation} from "crom_l1_composed/Relation";
import {GroupBase} from "crom_l1_composed/GroupBase";
import {RoleInheritanceBase} from "crom_l1_composed/RoleInheritanceBase";
import {RelationshipImplication} from "crom_l1_composed/RelationshipImplication";
import {DataType} from "crom_l1_composed/DataType";
import {AttributeBase} from "crom_l1_composed/AttributeBase";
import {RigidType} from "crom_l1_composed/RigidType";
import {DataInheritanceBase} from "crom_l1_composed/DataInheritanceBase";
import {CompartmentType} from "crom_l1_composed/CompartmentType";
import {RigidTypeBase} from "crom_l1_composed/RigidTypeBase";
import {IntraRelationshipConstraint} from "crom_l1_composed/IntraRelationshipConstraint";
import {PlaceBase} from "crom_l1_composed/PlaceBase";
import {RelationshipImplicationBase} from "crom_l1_composed/RelationshipImplicationBase";
import {ModelBase} from "crom_l1_composed/ModelBase";
import {RelationTarget} from "crom_l1_composed/RelationTarget";
import {RoleConstraint} from "crom_l1_composed/RoleConstraint";
import {IntraRelationshipConstraintBase} from "crom_l1_composed/IntraRelationshipConstraintBase";
import {RoleTypeBase} from "crom_l1_composed/RoleTypeBase";
import {Type} from "crom_l1_composed/Type";
import {Cyclic} from "crom_l1_composed/Cyclic";
import {NaturalType} from "crom_l1_composed/NaturalType";
import {Relationship} from "crom_l1_composed/Relationship";
import {Total} from "crom_l1_composed/Total";
import {Model} from "crom_l1_composed/Model";
import {Parameter} from "crom_l1_composed/Parameter";
import {RelationshipExclusion} from "crom_l1_composed/RelationshipExclusion";
import {RelationshipBase} from "crom_l1_composed/RelationshipBase";
import {AntiRigidTypeBase} from "crom_l1_composed/AntiRigidTypeBase";
import {Place} from "crom_l1_composed/Place";
import {TypedElementBase} from "crom_l1_composed/TypedElementBase";
import {Set} from "ecore/Set";
/* import Ecore*/
export class TotalImpl
extends TotalBase
{
	public static allInstances_:Set<Total> = new Set<Total>();
	//implement your generated class here
}
